# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy MZ to AZURE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envKey_TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          envKey_TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          envkey_TWITCH_CHANNELS: ${{ secrets.TWITCH_CHANNELS }}
          envkey_TWITCH_USER_ID: ${{ secrets.TWITCH_USER_ID }}
          envkey_TWITCH_ROOM_ID: ${{ secrets.TWITCH_ROOM_ID }}
          envkey_TWITCH_USER_NAME: ${{ secrets.TWITCH_USER_NAME }}
          envKey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          envKey_AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}
          envkey_PORT: 3000
          envkey_TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          envKey_TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          envKey_EXTERNAL_URL: ${{ secrets.EXTERNAL_URL }}
          envKey_BROWSERLESS_URL: ${{ secrets.BROWSERLESS_URL }}
          envKey_BROWSERLESS_TOKEN: ${{ secrets.BROWSERLESS_TOKEN }}
          envKey_BROWSERLESS_VERSION: v1
          envKey_STATUS_URL: ${{ secrets.STATUS_URL }}
          envKey_WHITE_LIST_ADMINS: ${{ secrets.WHITE_LIST_ADMINS }}
          envKey_WHITE_LIST_EDITORS: ${{ secrets.WHITE_LIST_EDITORS }}
          envKey_BLACK_LIST_USERS: ${{ secrets.BLACK_LIST_USERS }}
          envKey_WHITE_LIST_USERS: ${{ secrets.WHITE_LIST_USERS }}
          envKey_FEATURE_TF_SPOTS: false
          envkey_AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          envkey_AZURE_OPENAI_ENDPOINT_BASE: ${{ secrets.AZURE_OPENAI_ENDPOINT_BASE }}
          envkey_AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          envkey_AZURE_OPENAI_VECTOR_STORE_ID: ${{ secrets.AZURE_OPENAI_VECTOR_STORE_ID }}
          envkey_OPENAI_MONGODB_URI: ${{ secrets.OPENAI_MONGODB_URI }}
          envkey_TWITCH_EVENTSUB_SECRET: ${{ secrets.TWITCH_EVENTSUB_SECRET }}
          envkey_TWITCH_HOSTNAME: ${{ secrets.TWITCH_HOSTNAME }}
          envkey_WHISPER_ENDPOINT: ${{ secrets.WHISPER_ENDPOINT }}
          envkey_AZURE_OPENAI_ASSISTANT_ID: ${{ secrets.AZURE_OPENAI_ASSISTANT_ID }}
          envkey_AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          envkey_AZURE_STORAGE_CONTAINER_NAME: transcriptions
          envkey_HA_ENDPOINT: ${{ secrets.HA_ENDPOINT }}
          envkey_HA_API_KEY: ${{ secrets.HA_API_KEY }}
          envKey_LOKI_BASIC_AUTH: ${{ secrets.LOKI_BASIC_AUTH }}
          envKey_LOKI_HOST: ${{ secrets.LOKI_HOST }}
          envKey_BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          envKey_BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          envKey_CUSTOM_REWARD_BUY_VIP: "3eb520c1-0ed9-4a91-a92e-e6df15d91832"
          envKey_CUSTOM_REWARD_STEAL_VIP: "97f03170-8e68-42cf-985b-b19c6b7269e0"
          envKey_CUSTOM_REWARD_REVOKE_VIP: "411d86cb-8980-441f-bd50-55da350be813"
          envKey_CUSTOM_REWARD_TIMEOUT: "e0c37b17-fa39-4e53-aeea-6ea5be8d13d1"
          envKey_CUSTOM_REWARD_IMMUNE_SLOT_1: "12921a5e-9378-4a77-8aeb-9a9ff4d4c9f5"
          envKey_CUSTOM_REWARD_IMMUNE_SLOT_2: "9d97792e-09ce-4ef4-9e5c-62bf7433a59e"
          envKey_CUSTOM_REWARD_IMMUNE_SLOT_3: "3282424a-7c94-457f-8156-e61740c8d250"
          envKey_CUSTOM_REWARD_IMMUNE_SLOT_4: "175c4c91-04ec-4279-a3ff-7530ce3071b5"
          envKey_CUSTOM_REWARD_IMMUNE_SLOT_5: "a6c97da4-214c-48b0-8ca8-a74d7a0fccb4"
          envKey_CUSTOM_REWARD_TITLE: "9a59710b-9b25-4a0d-8df2-b391b6308815"
          envKey_CUSTOM_REWARD_UNBAN: "7ec73a49-4235-444d-9a7f-27567cec8bd7"
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip * .env

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'twitch-mz-bot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5F8104D0F0DB4488AE974F3659C5C153 }}
          package: release.zip